{{- if and .Values.kthenaRouter.enabled .Values.kthenaRouter.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kthena-router-validating-webhook
  labels:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.labels" . | nindent 4 }}
  {{- if eq .Values.global.certManagementMode "cert-manager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kthena-router-webhook-cert
  {{- end }}
webhooks:
  - name: validate-modelroute.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-router-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/modelroute"
        port: {{ .Values.kthenaRouter.webhook.servicePort }}
      {{- if eq .Values.global.certManagementMode "manual" }}
      caBundle: {{ required "A caBundle is required for the kthena-router validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelroutes" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-modelserver.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-router-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/modelserver"
        port: {{ .Values.kthenaRouter.webhook.servicePort }}
      {{- if eq .Values.global.certManagementMode "manual" }}
      caBundle: {{ required "A caBundle is required for the kthena-router validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelservers" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
{{- end }}

