{{- if and .Values.kthenaRouter.enabled .Values.kthenaRouter.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kthena-router-validating-webhook
  labels:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.labels" . | nindent 4 }}
webhooks:
  - name: validate-modelroute.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-router-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/modelroute"
        port: {{ .Values.kthenaRouter.webhook.servicePort }}
      {{- if .Values.kthenaRouter.webhook.tls.autoGenerateCert }}
      caBundle: ""
      {{- else }}
      caBundle: {{ required "A caBundle is required when auto-generate-cert is disabled" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelroutes" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-modelserver.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-router-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/modelserver"
        port: {{ .Values.kthenaRouter.webhook.servicePort }}
      {{- if .Values.kthenaRouter.webhook.tls.autoGenerateCert }}
      caBundle: ""
      {{- else }}
      caBundle: {{ required "A caBundle is required when auto-generate-cert is disabled" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelservers" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
{{- end }}

